version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DATABASE_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env


  app:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A config worker -l INFO -P eventlet
    depends_on:
      - db
      - redis
    env_file:
      - .env
